import type { Metadata } from "next";
import { Arimo } from "next/font/google";
import "./globals.css";
import Model from "./components/Model";

const arimo = Arimo({
  weight: ["400", "700"],
  subsets: ["latin"],
  variable: "--font-arimo",
});

export const metadata: Metadata = {
  title: "TMDB-API",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${arimo.className}`}>
        <Model />
        {children}
      </body>
    </html>
  );
}
